[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_test = "9wQw4F89uTFBwKDFq28EnnP5GqP3Bf3quQsvcNEje94R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
